"""Draft a DO-178C objective table from the verification report.

Rule-based mapping; each row links an objective bucket to the evidence that
currently addresses it (or to the string 'NOT YET' if no evidence exists).
The output is a markdown file prefixed with a DRAFT banner.
"""
from __future__ import annotations
import json
from pathlib import Path


_OBJECTIVES = [
    ("Software planning", "docs/M1/plan/, docs/M2/plan/, ..., docs/M6/plan/"),
    ("Software requirements", "docs/M1/requirements/requirements-tree.md + requirements.csv"),
    ("Software design", "docs/M1/architecture/, docs/M3/* design notes, ICD v0"),
    ("Source code", "tools/sim_py/avx_sim/*"),
    ("Verification of requirements", "tools/runner + evidence/verification-report.json"),
    ("Structural coverage (statement)", "tools/coverage_reporter (sys.settrace)"),
    ("Structural coverage (MC/DC)", "tools/sim_py/avx_sim/mcdc.py on designated decisions"),
    ("Configuration management", "git + evidence bundle manifest sha256"),
    ("Quality assurance", ".github/workflows/ci.yml gate"),
    ("Tool qualification", "docs/M1/certification/tool-qualification.md"),
]


def draft_do178c_objective_table(report_path: str | Path) -> str:
    data = json.loads(Path(report_path).read_text(encoding="utf-8"))
    s = data.get("summary", {})
    header = (
        "# DO-178C objective mapping (DRAFT)\n\n"
        "> DRAFT - human-in-the-loop. Generated by "
        "`tools/ai_assistant/artifact_draft.py`. Learning-grade mapping only, "
        "not a certification artifact.\n\n"
    )
    table = "| Objective | Evidence | Status |\n|---|---|---|\n"
    for obj, evidence in _OBJECTIVES:
        status = "addressed"
        if "MC/DC" in obj:
            status = f"{s.get('mcdc_pct_avg', 0)}% on instrumented decisions"
        elif "statement" in obj:
            status = f"{s.get('coverage_pct', 0)}%"
        elif "Verification of requirements" in obj:
            status = f"{s.get('tests_passed', 0)}/{s.get('tests_total', 0)} passing"
        table += f"| {obj} | {evidence} | {status} |\n"
    return header + table + "\n"
