"""Generate a human-readable markdown summary from a verification report."""
from __future__ import annotations
import json
from pathlib import Path


def summarize_evidence_markdown(report_path: str | Path) -> str:
    data = json.loads(Path(report_path).read_text(encoding="utf-8"))
    s = data.get("summary", {})
    lines: list[str] = []
    lines.append("# Evidence summary (DRAFT)")
    lines.append("")
    lines.append("> DRAFT - human-in-the-loop. Generated by "
                 "`tools/ai_assistant/evidence_summary.py`.")
    lines.append("")
    lines.append("## Headline numbers")
    lines.append(f"- Tests: {s.get('tests_passed', 0)}/{s.get('tests_total', 0)} passing")
    lines.append(f"- Campaigns: {s.get('campaigns_passed', 0)}/{s.get('campaigns_total', 0)} passing")
    lines.append(f"- Line coverage (avx_sim): **{s.get('coverage_pct', 0)}%**")
    lines.append(f"- MC/DC (instrumented decisions): **{s.get('mcdc_pct_avg', 0)}%**")
    lines.append(f"- HF evaluations: {s.get('hf_passed', 0)}/{s.get('hf_total', 0)} passing")
    lines.append(f"- Mode-confusion scenarios: {s.get('mode_confusion_ok', 0)}"
                 f"/{s.get('mode_confusion_total', 0)} green")
    lines.append(f"- HIL-lite runs: {s.get('hil_runs', 0)}")
    lines.append(f"- Uncovered requirements: {s.get('gap_uncovered_count', 0)}")
    lines.append("")

    campaigns = data.get("campaigns", [])
    if campaigns:
        lines.append("## Fault-injection campaigns")
        for c in campaigns:
            lines.append(
                f"- **{c.get('id', '?')}** classification="
                f"`{c.get('classification', '?')}` mode="
                f"`{c.get('fcc_mode_terminal', '?')}` hm_events="
                f"{c.get('hm_event_total', 0)}"
            )
        lines.append("")

    hil = data.get("hil_runs", [])
    if hil:
        lines.append("## HIL-lite runs")
        for r in hil:
            lines.append(
                f"- `{r.get('name')}` cycles={r.get('cycles')} "
                f"lat_mean={r.get('latency_mean_us')}us "
                f"lat_max={r.get('latency_max_us')}us "
                f"drops={r.get('drops')} reboots={r.get('reboots')}"
            )
        lines.append("")

    return "\n".join(lines) + "\n"
