"""Generate JSON test-case skeletons from requirements.csv.

This is a deterministic rule-based "AI" that turns a requirement row into a
starter ``tools/runner/test_cases/TC-*.json`` file. The goal is NOT to
auto-verify anything — it's to remove the blank-page problem for engineers
so every requirement gets at least an empty placeholder test case with the
right metadata.

Every generated file is labelled DRAFT so no human is misled into trusting
it as a real verification artifact.
"""
from __future__ import annotations
import csv
import json
from pathlib import Path


DRAFT_BANNER = "DRAFT - human-in-the-loop. Generated by ai_assistant; review before use."


def _world_for(req_id: str) -> dict:
    if "FCC" in req_id:
        return {"seed": 1, "force_dual_fault_at_us": 50_000}
    if "ENG" in req_id:
        return {"seed": 1, "n1_at_t1s": 104.0}
    if "DSP" in req_id:
        return {"seed": 1}
    return {"seed": 1}


def _expects_for(req_id: str) -> dict:
    if "FCC" in req_id:
        return {"fcc_mode_terminal": "NORMAL"}
    if "ENG" in req_id:
        return {"engine_state_min": "WARNING"}
    return {"msg_ids_present": ["MSG-001"]}


def generate_test_skeletons(req_csv: str | Path, out_dir: str | Path,
                            *, only_prefixes: tuple[str, ...] = ("HLR",),
                            overwrite: bool = False) -> list[Path]:
    """Read ``req_csv`` and emit one JSON skeleton per HLR (by default).
    Returns the list of files written."""
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    with open(req_csv, encoding="utf-8") as fh:
        for row in csv.DictReader(fh):
            rid = row.get("id", "")
            if not rid.startswith(only_prefixes):
                continue
            path = out / f"TC-{rid}-draft.json"
            if path.exists() and not overwrite:
                continue
            body = {
                "_draft": DRAFT_BANNER,
                "id": f"TC-{rid}-draft",
                "req": [rid],
                "description": f"DRAFT skeleton for {rid}: {row.get('text', '')[:80]}",
                "duration_ms": 200,
                "world": _world_for(rid),
                "expects": _expects_for(rid),
            }
            path.write_text(json.dumps(body, indent=2), encoding="utf-8")
            written.append(path)
    return written
