"""Turn escaped fault campaigns into candidate requirement entries and link
them to the failure-condition catalog in ``docs/M1/certification/safety.md``.

Rule of thumb: if a campaign is classified ``escaped`` there is (at least)
one missing requirement or test — the system observed a fault without
raising an HM event and without entering a degraded mode. This helper
writes a DRAFT markdown file so the engineer reviews and either files a new
requirement or justifies the escape.
"""
from __future__ import annotations
from dataclasses import dataclass
from pathlib import Path


FC_HINTS = {
    "afdx_delay":   "FC-10",   # bus storm / latency spike
    "ias_drift":    "FC-04",   # erroneous air data
    "n1_at_t1s":    "FC-07",   # engine exceedance not annunciated
    "egt_at_t1s":   "FC-07",
    "force_dual_fault_at_us": "FC-02",  # erroneous attitude (covered)
    "afdx_drop_every_n": "FC-10",
}


@dataclass
class EscapeCandidate:
    campaign_id: str
    fault_hint: str
    fc_id: str
    proposed_req: str


def _fault_hint(campaign_faults: list[dict]) -> str:
    if not campaign_faults:
        return ""
    return campaign_faults[0].get("type", "")


def collect_escapes(campaigns: list[dict]) -> list[EscapeCandidate]:
    out: list[EscapeCandidate] = []
    for c in campaigns:
        if c.get("classification") != "escaped":
            continue
        # campaigns.json doesn't carry the original faults, so callers that
        # have the source JSON can pass a richer object. We fall back to
        # extracting from the id.
        hint = c.get("_fault_hint", "")
        fc = FC_HINTS.get(hint, "FC-??")
        req = f"REQ-CANDIDATE-{c['id']}"
        out.append(EscapeCandidate(
            campaign_id=c["id"], fault_hint=hint, fc_id=fc,
            proposed_req=req,
        ))
    return out


def render_markdown(escapes: list[EscapeCandidate]) -> str:
    header = (
        "# Escape candidates (DRAFT)\n\n"
        "> DRAFT - human-in-the-loop. Generated by "
        "`tools/fault_injector/escape.py`. Each row is a proposed new "
        "requirement; do NOT merge without review.\n\n"
    )
    if not escapes:
        return header + "_No escapes recorded in this run._\n"
    rows = ["| Campaign | Fault | FC | Proposed requirement |",
            "|---|---|---|---|"]
    for e in escapes:
        rows.append(
            f"| {e.campaign_id} | `{e.fault_hint}` | {e.fc_id} | `{e.proposed_req}` |"
        )
    return header + "\n".join(rows) + "\n"


def write_markdown(escapes: list[EscapeCandidate], out_path: str | Path) -> Path:
    p = Path(out_path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(render_markdown(escapes), encoding="utf-8")
    return p
